config/routes.rb
Rails.application.routes.draw do
  resources :sheets do
    resources :api_keys, only: [:create]
    resources :visuals, only: [:index] do
      collection do
        get :data
      end
    end
  end

  resources :onboarding, only: [:index, :show, :create] do
    member do
      get ":worksheet_id", to:  "onboarding#worksheet", as: :worksheet
    end
  end

  root to: 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]

  get "/auth/:provider/callback" => 'sessions#create'
  get "logout" => 'sessions#destroy'
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
  belongs_to :user
  has_many :worksheet_rows
  has_many :api_keys
  serialize :headers, JSON
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_filter :require_login, except: [:show]

  def index
    @sheets = current_user.sheets.includes(:api_keys)
  end

  def show
    @key = nil
    @sheet = nil


    if current_user

      # if someone is logged in, go ahead and show
      @sheet = current_user.sheets.find(params[:id])
    elsif params[:token].present?

      # if a token is provided, use it
      @key = ApiKey.includes(:sheet).where(sheet_id: params[:id], id: params[:token]).first!
      @sheet = @key.sheet

      # keep track of the token use_count
      @key.increment!(:use_count)
    end

    if @sheet.blank?
      render(json: {error: "not found"}, code: 404) and return
    end

    rows = @sheet.worksheet_rows.order('row ASC').paginate(page: params[:page], per_page: 100)

    args = {only: [:title, :use_count]}

    if @sheet.use_headers
      args[:only] ||= []
      args[:only] << :headers
    end

    @json_response = @sheet.as_json(args).merge({rows: rows.pluck(:data), meta: pagination_dict(rows)})

    respond_to do |format|
      format.html
      format.json { render json: @json_response }
    end
  end

  def pagination_dict(collection)
    {
        current_page: collection.current_page,
        next_page: collection.next_page,
        total_pages: collection.total_pages
    }
  end

end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/sheets/index.html.erb
<h2>Your Sheets</h2>

<%= link_to("import another sheet", onboarding_index_path) %>

<ol>
  <% @sheets.each do |sheet| %>
      <li>
        <dl>
          <dt>Title</dt>
          <dd>
            <%= link_to(sheet.title, sheet_path(sheet)) %>
            <%= link_to "Visualize This Sheet", sheet_visuals_path(sheet) %>
          </dd>

          <dt>Created</dt>
          <dd><%= time_ago_in_words(sheet.created_at) %></dd>

          <dt>WorkSheet Rows</dt>
          <dd><%= sheet.worksheet_rows_count %></dd>

          <dt>External Link to Google</dt>
          <% link = "https://docs.google.com/spreadsheets/d/#{sheet.google_file_id}/edit#gid=#{sheet.google_worksheet_id}" %>
          <dd><%= link_to(link, link, target: "_blank") %></dd>

          <dt>Api Keys</dt>
          <dd>
            <ul>
              <% sheet.api_keys.each do |key| %>
                  <li>
                    (<%= key.use_count %>)
                    <%= text_field_tag(nil, key.id) %>
                    <% path_tester = sheet_path(sheet, token: key.id, format: :json) %>
                    <%= link_to "test", path_tester, title: path_tester  %>
                  </li>
              <% end %>
            </ul>
          </dd>
        </dl>
      </li>
  <% end %>
</ol>

app/views/sheets/show.html.erb
<%= link_to "Visualize This Sheet", sheet_visuals_path(@sheet) %>
<%= button_to "Generate ApiKey", sheet_api_keys_path(@sheet) %>
<% if @sheet.api_keys.length > 0 %>
    <p>Right-Click and open link in an incognito browser</p>
    <ul>
      <% @sheet.api_keys.each do |key| %>
          <li>
            (<%= key.use_count %>)
            <% if Rails.env.production? %>
                <%= link_to sheet_url(@sheet, token: key.id, format: :json), sheet_url(@sheet, token: key.id, format: :json) %>
            <% else %>
                <%= link_to sheet_path(@sheet, token: key.id, format: :json), sheet_path(@sheet, token: key.id, format: :json) %>
            <% end %>
          </li>
      <% end %>
    </ul>
<% end %>

<pre><%= JSON.pretty_generate(@json_response) %></pre>